### ISSUE TITLE
解析CSV文件会出现EOF错误

### ISSUE THREAD

**Issue by LiJianShu0826** [master-g/i18n#2]
解析CSV文件时，没有忽略IO.EOF错误

**Comment by master-g** [comment]
请问有复现路径吗？

**Comment by LiJianShu0826** [comment]
随便使用一个csv文件就能复现。或者试一试下面的文件。EOF异常应该特殊处理一下
[resource.csv](https://github.com/user-attachments/files/17829832/resource.csv)

**Comment by master-g** [comment]
很遗憾，这边使用您提供的例子无法复现，在 M2 的 macbook Sequoia 15.0.1 上
请确认一下是不是输出目录的问题，也可以使用 --dry 模式检查一下
